### ISSUE TITLE
Testing Bonsai sites with Cucumber and Webrat

### ISSUE THREAD

**Issue by ornamentist** [benschwarz/bonsai#6]
I'm not sure this is an "issue" as such, but I was wondering if anyone is using Cucumber and/or Webrat for testing static sites generated with Bonsai?

Stu

**Comment by benschwarz** [comment]
Hey Stu, I probably would've posted on the google group instead but its really fine.
I haven't heard of anyone using cucumber to test a bonsai site. 

I don't have a lot of bandwidth right now so if you want to have a stab and send me a patch I'd be happy to look over it on the weekend or something. 

Otherwise I'll leave it in mind.

**Comment by ornamentist** [comment]
Now I think about it more Cucumber testing doesn't need to be integrated into Bonsai just yet--it can sit alongside the top level Bonsai directories.  Here's a useful blog post of someone doing this to "specify" a Google search:

http://blog.jcoglan.com/2009/10/03/getting-started-with-cucumber-rspec-webrat-and-multiruby/

**Comment by benschwarz** [comment]
Good stuff. After thinking about it I didn't want to provision for this. I feel as though this can be done externally easily enough for those who wish to.
